/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js", "./admin/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Rose de la marque (issu du logo) — couleur principale du site.
        pink: "#e6338d",
        "on-pink": "#ffffff",
        // Vert citron de la marque (issu du logo) — seconde couleur dominante.
        citron: "#7cbc10",
        "on-citron": "#ffffff",
        // Orange de la marque — touche d'accent ponctuelle, pas une couleur
        // dominante.
        orange: "#f2762e",
        "on-orange": "#ffffff",
        // Bleu ciel — touche d'accent professionnelle supplémentaire, utilisée
        // ponctuellement (ex. bilinguisme/international).
        sky: "#1E88C0",
        "on-sky": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-low": "#f8f2fa",
        "outline-variant": "#cbc4d2",
        "on-surface": "#1d1b20",
        "surface-variant": "#e6e0e9",
        error: "#ba1a1a",
        // ---- Primary = rose (couleur principale du site, remplace le violet) ----
        primary: "#e6338d",
        "on-primary": "#ffffff",
        "primary-container": "#ffd8ea",
        "on-primary-container": "#5c0036",
        "primary-fixed": "#ffd8ea",
        "primary-fixed-dim": "#ffabd4",
        "on-primary-fixed": "#3a0021",
        "on-primary-fixed-variant": "#7a0049",
        "surface-tint": "#e6338d",
        "inverse-primary": "#ffb0d6",
        // ---- Secondary = vert citron (seconde couleur dominante) ----------------
        secondary: "#4c7a0a",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2f2c4",
        "on-secondary-container": "#2b4600",
        "secondary-fixed": "#e2f2c4",
        "secondary-fixed-dim": "#c1e086",
        "on-secondary-fixed": "#1b2e00",
        "on-secondary-fixed-variant": "#395c07",
        // ---- Tertiary = orange (touches d'accent) --------------------------------
        tertiary: "#9c4a12",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffddc2",
        "on-tertiary-container": "#5c2100",
        "tertiary-fixed": "#ffddc2",
        "tertiary-fixed-dim": "#ffb787",
        "on-tertiary-fixed": "#3d1300",
        "on-tertiary-fixed-variant": "#7a3300",
        "on-surface-variant": "#494551",
        outline: "#7a7582",
        "inverse-surface": "#322f35",
        "surface-dim": "#ded8e0",
        "surface-container-high": "#ece6ee",
        surface: "#fdf7ff",
        background: "#fdf7ff",
        "inverse-on-surface": "#f5eff7",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1d1b20",
        "surface-bright": "#fdf7ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container": "#f2ecf4",
        "surface-container-highest": "#e6e0e9",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "headline-xl": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 10px 40px -10px rgba(230, 51, 141, 0.08)",
      },
    },
  },
  plugins: [],
};
