/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js", "./admin/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Rose de la marque (issu du logo), utilisé avec parcimonie comme
        // touche d'accent aux côtés du violet principal.
        pink: "#e6338d",
        "on-pink": "#ffffff",
        "tertiary-container": "#c9a74d",
        "on-error": "#ffffff",
        "surface-container-low": "#f8f2fa",
        "outline-variant": "#cbc4d2",
        "on-surface": "#1d1b20",
        "surface-variant": "#e6e0e9",
        error: "#ba1a1a",
        primary: "#4f378a",
        "on-surface-variant": "#494551",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary": "#ffffff",
        outline: "#7a7582",
        "on-primary-container": "#e0d2ff",
        "surface-tint": "#6750a4",
        "tertiary-fixed": "#ffdf93",
        "on-secondary-container": "#645a7d",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#503d00",
        "on-tertiary-fixed": "#241a00",
        "primary-fixed": "#e9ddff",
        "on-secondary-fixed-variant": "#4b4263",
        "inverse-surface": "#322f35",
        "surface-dim": "#ded8e0",
        "on-primary": "#ffffff",
        "primary-container": "#6750a4",
        "surface-container-high": "#ece6ee",
        surface: "#fdf7ff",
        "on-tertiary-fixed-variant": "#594400",
        "secondary-container": "#e1d4fd",
        background: "#fdf7ff",
        tertiary: "#765b00",
        "inverse-on-surface": "#f5eff7",
        "secondary-fixed": "#e9ddff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#4f378a",
        "on-background": "#1d1b20",
        "surface-bright": "#fdf7ff",
        "on-secondary-fixed": "#1f1635",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#cdc0e9",
        secondary: "#63597c",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#22005d",
        "primary-fixed-dim": "#cfbcff",
        "surface-container": "#f2ecf4",
        "surface-container-highest": "#e6e0e9",
        "inverse-primary": "#cfbcff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "headline-xl": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 10px 40px -10px rgba(79, 55, 138, 0.08)",
      },
    },
  },
  plugins: [],
};
